### ISSUE TITLE
tag releases?

### ISSUE THREAD

**Issue by Barbarossa93** [albertored11/bsptab#2]
Hey there,

Thanks for sharing this! This is exactly what I've been looking for since I started using bspwm. I was wondering if you'd be willing to create a tag release? I'd be interested in packaging this for the void linux repos.

**Comment by albertored11** [comment]
Thanks for your words, I am happy that this little project is useful for others.

Sure, it's a good idea to create a tag release, I'll do it in a bit. And I'd really appreciate if you could let me know when the package is available so I can link it in the README.

**Comment by albertored11** [comment]
Done!
